language: python
python: '2.7'
matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27 
  - python: '2.7'
    env: TOXENV=py27-flake8 
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.6'
    env: TOXENV=py36-flake8
  allow_failures:
  - python: '3.6'
    env: TOXENV=py36
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
script:
  - make test
  - flake8 .
after_success:
  - codecov